#================================================================================================================================================
# You should be able to use any of the values you can find here: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#================================================================================================================================================
image:
  repository:
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 80
        targetPort: 80
#=============================
# Application-specific config
#=============================
tandoor:
  configSecret:
    existingSecret: ""

  postgres:
    enabled: false

    username: bazarr
    password: ""

    port: 5432
    host: postgres-cluster-rw.postgres.svc.cluster.local

    dbName: bazarr

#=============
# Subchart(s)
#=============
