{{- if .Values.authentik.enabled }}
# Technically not necessary, as one policy makes the whole cluster deny-by-default
# But we put this here so it's obvious
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: explicit-deny-all
  namespace: istio-system
spec: {}
---
# TODO Remove this as we move to a proper deny-by-default model
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-intra-cluster
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
      - source:
          principals:
            - "cluster.local/*"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-outpost-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
          {{- toYaml .Values.hostnames | nindent 14 }}
        paths:
        - /outpost.goauthentik.io
        - /outpost.goauthentik.io/*
  selector:
    matchLabels:
      app: istio-gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-outpost-ingress-allow
  namespace: authentik
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-gateway
    to:
    - operation:
        hosts:
          {{- toYaml .Values.hostnames | nindent 14 }}
        paths:
        - /outpost.goauthentik.io
        - /outpost.goauthentik.io/*
---
{{- range $hostname := .Values.hostnames }}
{{- $safeHostname := replace "." "-" $hostname }}
{{- $gatewayName = printf "shared-%s-gateway" $safeHostname }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authentik-outpost-{{$safeHostname}}
  namespace: istio-system
spec:
  hosts:
    - {{ $hostname }}
  gateways:
    - {{ $gatewayName }}
  http:
    - match:
      - uri:
          prefix: /outpost.goauthentik.io
      route:
        - destination:
            host: ak-outpost-proxy-outpost-{{ $safeHostname }}.authentik.svc.cluster.local
            port:
              number: 9000
---
{{- end }}
{{- end }}
