# Technically not necessary, as one policy makes the whole cluster deny-by-default
# But we put this here so it's obvious
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: explicit-deny-all
  namespace: istio-system
spec: {}
---
# TODO Remove this as we move to a proper deny-by-default model
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-intra-cluster
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
      - source:
          principals:
            - "cluster.local/*"
---
{{- range $ingressName, $ingress := .Values }}
{{- if ne $ingressName "hostnames" }}
{{- $create := not (hasKey $ingress "multiHost" | ternary $ingress.multiHost false) }}
{{- if and $ingress.enabled $ingress.destinationSvc $create }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $ingressName }}-ingress-authentik
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: authentik
  rules:
    - to:
      - operation:
          hosts:
            {{- if $ingress.subdomain }}
            {{- range .Values.hostnames }}
            - {{ $ingress.subdomain }}.{{ . }}
            {{- end }}
            {{- else }}
            {{- range $.Values.hostnames }}
            - {{ . }}
            {{- end }}
            {{- end }}
          {{- if not $ingress.subdomain }}
          paths:
            {{- range $ingress.prefixes }}
            - {{ . }}
            - {{ . }}/*
            {{- end }}
          {{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prowlarr-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
          {{- if $ingress.subdomain }}
          {{- range .Values.hostnames }}
          - {{ $ingress.subdomain }}.{{ . }}
          {{- end }}
          {{- else }}
          {{- range .Values.hostnames }}
          - {{ . }}
          {{- end }}
          {{- end }}
        {{- if not $ingress.subdomain }}
        paths:
          {{- range $ingress.prefixes }}
          - {{ . }}
          - {{ . }}/*
          {{- end }}
        {{- end }}
  selector:
    matchLabels:
      app: istio-gateway
{{- end }}
{{- end }}
{{- end }}