{{- range $ingressName, $ingress := .Values }}
{{- if ne $ingressName "hostnames" }}
{{- $create := not (hasKey $ingress "multiHost" | ternary $ingress.multiHost false) }}
{{- $enabled := or $ingress.enabled (include "common.isItemEnabled" (dict "item" $ingress "Values" $.Values))}}
{{- $ingressDetails := include "common.mergeGroupOverrides" (dict "item" $ingress "itemName" $ingressName) | fromYaml }}
{{- if and $enabled $create $ingress.destinationSvc }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $ingressName }}
  namespace: {{ $ingressDetails.namespace | default "istio-system" }}
spec:
{{- with $.Values.hostnames }}
  hosts:
  {{- range . }}
    {{- if $ingressDetails.subdomain }}
      {{- if not (regexMatch "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$" .) }}
    - {{ $ingressDetails.subdomain }}.{{ . }}
      {{- end }}
    {{- else }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
  gateways:
    - internal-gateway
  http:
    - match:
      {{- $prefixes := $ingressDetails.prefixes | default (list "/") }}
      {{- range $prefixes }}
        - uri:
            prefix: {{ . }}
      {{- end }}
      {{- with $ingressDetails.rewrite }}
      rewrite:
        {{- toYaml . | nindent 7}}
      {{- end }}
      route:
        - destination:
            host: {{ $ingressDetails.destinationSvc }}
            port:
              number: {{ $ingressDetails.destinationPort | default 80}}
        {{- with $ingressDetails.headers }}
          headers:
            {{- toYaml . | nindent 12 }}
        {{- end }}
---
{{- end }}
{{- end }}
{{- end }}