apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - iam.qa-cluster-lb.lan
        - iam.qa-cluster-lb.lan:443
        - iam.qa-cluster-lb.lan:80
  selector:
    matchLabels:
      app: istio-gateway
---
# FILE: authentik-ingress-allow.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-ingress-allow
  namespace: authentik
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-gateway
    to:
    - operation:
        hosts:
        - iam.qa-cluster-lb.lan
        - iam.qa-cluster-lb.lan:*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: argocd-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /argocd
        - /argocd/*
  selector:
    matchLabels:
      app: istio-gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: argocd-ingress-allow
  namespace: argocd
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-gateway
    to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /argocd
        - /argocd/*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-outpost-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /outpost.goauthentik.io
        - /outpost.goauthentik.io/*
  selector:
    matchLabels:
      app: istio-gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authentik-outpost-ingress-allow
  namespace: authentik
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-gateway
    to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /outpost.goauthentik.io
        - /outpost.goauthentik.io/*
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authentik-outpost
  namespace: istio-system
spec:
  hosts:
    - qa-cluster-lb.lan
  gateways:
    - internal-gateway
  http:
    - match:
      - uri:
          prefix: /outpost.goauthentik.io
      route:
        - destination:
            host: ak-outpost-main-outpost.authentik.svc.cluster.local
            port:
              number: 9000
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prowlarr-ingress-istio
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /prowlarr
        - /prowlarr/*
  selector:
    matchLabels:
      app: istio-gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prowlarr-ingress-allow
  namespace: videos
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/videos/sa/prowlarr
    to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /prowlarr
        - /prowlarr/*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prowlarr-ingress-custom
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: authentik
  rules:
  - to:
    - operation:
        hosts:
        - qa-cluster-lb.lan
        paths:
        - /prowlarr
        - /prowlarr/*
        notPaths:
        - /outpost.goauthentik.io/*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-outpost-to-server
  namespace: authentik
spec:
  action: ALLOW
  rules:
    - from:
      - source:
          namespaces: ["authentik"]