gfd:
  enabled: true

runtimeClassName: nvidia

cdi:
  nvidiaHookPath: /usr/bin/nvidia-ctk

config:
  map:
    default: |-
      version: v1
      flags:
        migStrategy: none
        plugin:
          deviceListStrategy: "envvar"
          deviceIDStrategy: "uuid"
          nvidiaCTKPath: /usr/bin/nvidia-ctk
          passDeviceSpecs: true
