gfd:
  enabled: true

deviceDiscoveryStrategy: nvml
# runtimeClassName: nvidia

config:
  map:
    default: |
      version: v1
      flags:
        migStrategy: none
      cdi:
        enabled: true
        default: true

mps:
  enableHostPID: true

cdi:
  nvidia-hook-path: /usr/bin/nvidia-ctk
