{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "bazarr.harcodedValues" -}}
  {{- if .Values.bazarr.postgres.enabled }}
env:
  {{- $defaultSecretName := printf "%v-%v" .Release.Name "config-secret" }}
  - name: POSTGRES_HOST
    value: {{ .Values.bazarr.postgres.host }}
  - name: POSTGRES_DATABASE
    value: {{ .Values.bazarr.postgres.dbName }}
  - name: POSTGRES_PORT
    value: {{ .Values.bazarr.postgres.port | quote }}
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: {{ .Values.bazarr.configSecret.existingSecret | default $defaultSecretName }}
        key: postgresUsername
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ .Values.bazarr.configSecret.existingSecret | default $defaultSecretName}}
        key: postgresPassword
  {{- end }}

{{- if .Values.bazarr.configYamlSecret.enabled }}
persistence:
  config:
    type: secret
    name: {{ .Values.bazarr.configYamlSecret.existingSecret | default "bazarr-config-yaml" }}
    mountPath: /config/config

{{- end }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "bazarr.harcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}