{{- range $appName, $app := .Values }}
{{- $excludedNames := (list "env" "hostnames" "defaultGitRepo" "gitRevision" "configuration")}}
{{- if not (has $appName $excludedNames) }}
{{- $create := not (hasKey $app "multiHost" | ternary $app.multiHost false) }}
{{- $appDetails := include "common.mergeGroupOverrides" (dict "item" $app "itemName" $appName "Values" $.Values) | fromYaml }}
{{- $enabled := or $app.enabled (include "common.isItemEnabled" (dict "item" $app "Values" $.Values)) }}
{{- if and $enabled $create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: argocd
  annotations:
  {{- if $appDetails.syncWave }}
    argocd.argoproj.io/sync-wave: "{{ $appDetails.syncWave }}"
  {{- end }}
  {{- if $appDetails.syncOptions }}
    argocd.argoproj.io/compare-options: "{{ $appDetails.syncOptions }}"
  {{- end }}
spec:
  project: default
  sources:
    - repoURL: {{ $appDetails.repo | default $.Values.defaultGitRepo }}
      targetRevision: {{ $appDetails.version | default $.Values.gitRevision }}
    {{- with $appDetails.gitPath }}
      path: {{ tpl . $ }}
    {{- end }}
    {{- with $appDetails.chart }}
      chart: {{ . }}
    {{- end }}
    {{- $isHelmChart := and (not (hasKey $appDetails "secureValues")) (or (not (hasKey $appDetails "helmChart")) $appDetails.helmChart) }}
    {{- if $isHelmChart }}
      helm:
        {{- if and $appDetails.defaultValues (not (($appDetails.configuration).enabled | default false)) }}
        values:
          {{ tpl $appDetails.defaultValues $ | toYaml | indent 8 }}
        {{- end }}
        releaseName: {{ $appName }}
      {{- if ($appDetails.configuration).enabled }}
        valueFiles:
          - "$values/{{ $.Values.configuration.configurationDirectory }}/{{ $.Values.env }}/{{ $appName }}.yaml"
    - repoURL: {{ $.Values.configuration.configurationRepo }}
      targetRevision: {{ $.Values.configuration.configurationRevision | default $.Values.gitRevision }}
      ref: values
      {{- end }}
    {{- else if $appDetails.secureValues }}
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value:
              {{- $appDetails.secureValues | toYaml | indent 12 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
  {{- if $appDetails.destinationNamespace }}
    namespace: {{ $appDetails.destinationNamespace }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- if $appDetails.serverSideApply }}
      - ServerSideApply=true
      {{- end }}
---
{{- range $subAppName, $subApp := $app.dependentApps }}
{{- $enabled := ternary $subApp.enabled true (hasKey $subApp "enabled") }}
{{- if and (ne $subAppName "homepage-config") $enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $subAppName }}
  namespace: argocd
  annotations:
  {{- $syncWave := $subApp.syncWave | default $app.syncWave }}
  {{- $syncOptions := $subApp.syncOptions | default $app.syncOptions }}
  {{- if $syncWave }}
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  {{- end }}
  {{- if $syncOptions }}
    argocd.argoproj.io/compare-options: "{{ $syncOptions }}"
  {{- end }}
spec:
  project: default
  sources:
    - repoURL: {{ $subApp.repo | default $app.repo }}
    {{- if $subApp.useDefaultGitRevision }}
      targetRevision: {{ $.Values.gitRevision }}
    {{- else }}
      targetRevision: {{ $subApp.version | default $app.version }}
    {{- end }}
    {{- with $subApp.gitPath }}
      path: {{ tpl . $ }}
    {{- end }}
    {{- with $subApp.chart }}
      chart: {{ . }}
    {{- end }}
    {{- $isHelmChart := and (not (hasKey $subApp "secureValues")) (or (not (hasKey $subApp "helmChart")) $subApp.helmChart ) }}
    {{- if $isHelmChart }}
      helm:
        {{- if or $subApp.defaultValues $subApp.followMasterConfig }}
        values:
          {{- with $subApp.defaultValues }}
          {{- tpl . $ | toYaml | indent 8 }}
          {{- end }}
          {{- if $subApp.followMasterConfig }}
          {{- include "common.generateEnabledValues" (dict "passThroughKeys" (list "hostnames") "Values" $.Values) | toYaml | indent 8 }}
          {{- end }}
        {{- end }}
        releaseName: {{ $subAppName }}
      {{- if ($subApp.configuration).enabled }}
        valueFiles:
          - "$values/{{ $.Values.configuration.configurationDirectory }}/{{ $.Values.env }}/{{ $subAppName }}.yaml"
    - repoURL: {{ $.Values.configuration.configurationRepo }}
      targetRevision: {{ $.Values.configuration.configurationRevision | default $.Values.gitRevision }}
      ref: values
      {{- end }}
    {{- else if $subApp.secureValues }}
      plugin:
        name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value:
            {{- $subApp.secureValues | toYaml | indent 8 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
  {{- $destinationNamespace := $subApp.destinationNamespace | default $app.destinationNamespace }}
  {{- if $destinationNamespace }}
    namespace: {{ $destinationNamespace }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- if $subApp.serverSideApply }}
      - ServerSideApply=true
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}