{{- range $appName, $app := .Values }}
{{- $excludedNames := (list "env" "hostnames" "defaultGitRepo" "gitRevision" "configuration")}}
{{- if not (has $appName $excludedNames) }}
{{- $appDetails := include "common.mergeGroupOverrides" (dict "item" $app "itemName" $appName "Values" $.Values) | fromYaml }}
{{- $enabled := or $appDetails.enabled (include "common.isAppEnabled" (dict "item" $app "Values" $.Values)) }}
{{- if and $enabled ($appDetails.multiHost | default false)}}
{{- range $hostname := $.Values.hostnames }}
{{- $safeHostname := $hostname | replace "." "-" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $appName }}-{{ $safeHostname }}"
  namespace: argocd
  annotations:
  {{- if $appDetails.syncWave }}
    argocd.argoproj.io/sync-wave: "{{ $appDetails.syncWave }}"
  {{- end }}
  {{- if $appDetails.syncOptions }}
    argocd.argoproj.io/compare-options: "{{ $appDetails.syncOptions }}"
  {{- end }}
spec:
  project: default
  sources:
    - repoURL: {{ $appDetails.repo | default $.Values.defaultGitRepo }}
      targetRevision: {{ $appDetails.version | default $.Values.gitRevision }}
    {{- with $appDetails.gitPath }}
      path: {{ tpl . $ }}
    {{- end }}
    {{- with $appDetails.chart }}
      chart: {{ . }}
    {{- end }}
    {{- $isHelmChart := and (not (hasKey $app "secureValues")) (or (not (hasKey $app "helmChart")) $appDetails.helmChart) }}
    {{- if $isHelmChart }}
      helm:
        values: |
          env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: {{ $hostname }}
          config:
            useExistingConfigMap: homepage-config-{{ $safeHostname }}
        releaseName: "{{ $appName }}-{{ $safeHostname }}"
      {{- if ($appDetails.configuration).enabled }}
        valueFiles:
          - "$values/{{ $.Values.configuration.configurationDirectory }}/{{ $.Values.env }}/{{ $appName }}.yaml"
    - repoURL: {{ $.Values.configuration.configurationRepo }}
      targetRevision: {{ $.Values.configuration.configurationRevision | default $.Values.gitRevision }}
      ref: values
      {{- end }}
    {{- else if $appDetails.secureValues }}
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value:
              {{- $appDetails.secureValues | toYaml | indent 12 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
  {{- if $appDetails.destinationNamespace }}
    namespace: {{ $appDetails.destinationNamespace }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- if $appDetails.serverSideApply }}
      - ServerSideApply=true
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}