// Package cogtoml implements the hybrid fixed/generated cog.toml
// strategy: everything above a marker comment is opaque, hand-owned
// text that this tool never touches. Everything below the marker is
// the [packages.*] tables, fully recomputed from the discovered image
// directories on every run, with the exception of a small set of
// "extra" keys a human may have added to a package table by hand —
// those are preserved across regeneration.
package cogtoml

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
	"sync-cog-packages/internal/discover"
)

// Marker is the line that divides the fixed, hand-maintained section
// of cog.toml from the generated [packages.*] section below it. It
// must appear verbatim and exactly once in cog.toml.
const Marker = "# ==== GENERATED BY sync-cog-packages: DO NOT HAND-EDIT BELOW THIS LINE ===="

// reservedKeys are the fields sync-cog-packages always computes itself
// and overwrites on every run. Any other key found in an existing
// package table is treated as a human-added override and preserved.
var reservedKeys = map[string]bool{
	"path":           true,
	"changelog_path": true,
	"tag_prefix":     true,
	"bump_hooks":     true,
}

// GeneratedPackage is the fully-resolved set of fields for one
// [packages.<name>] table, ready to render.
type GeneratedPackage struct {
	Name          string
	Path          string
	ChangelogPath string
	TagPrefix     string
	BumpHooks     []string
	// Extra holds preserved hand-added keys, key -> raw TOML value
	// (already formatted, e.g. `"foo"`, `true`, `[1, 2]`).
	Extra map[string]string
}

// Diff summarizes what would change in a run, for --check mode.
type Diff struct {
	Added   []string
	Removed []string
	Changed []string
}

func (d Diff) Empty() bool {
	return len(d.Added) == 0 && len(d.Removed) == 0 && len(d.Changed) == 0
}

// bareKeyRe matches strings that are valid as an unquoted TOML key.
var bareKeyRe = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

func tomlKey(k string) string {
	if bareKeyRe.MatchString(k) {
		return k
	}
	return strconv.Quote(k)
}

// Split separates raw cog.toml content into the fixed prefix (including
// the marker line and its trailing newline) and the generated suffix
// that follows it.
func Split(content string) (fixedPrefix, generatedSuffix string, err error) {
	idx := strings.Index(content, Marker)
	if idx == -1 {
		return "", "", fmt.Errorf(
			"cog.toml does not contain the marker line:\n  %s\n"+
				"add it once, above where the generated [packages.*] tables should live",
			Marker,
		)
	}
	end := idx + len(Marker)
	// Include the marker itself, plus the newline right after it, in
	// the fixed prefix so the generated section starts clean.
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return content[:end], content[end:], nil
}

// ParseExistingExtras decodes the existing generated section (if any)
// and returns, per package name, the set of non-reserved keys found —
// these are hand-added overrides that must survive regeneration.
func ParseExistingExtras(generatedSuffix string) (map[string]map[string]string, error) {
	var doc struct {
		Packages map[string]map[string]interface{} `toml:"packages"`
	}
	if strings.TrimSpace(generatedSuffix) == "" {
		return map[string]map[string]string{}, nil
	}
	if _, err := toml.Decode(generatedSuffix, &doc); err != nil {
		return nil, fmt.Errorf("parsing existing generated section: %w", err)
	}

	extras := map[string]map[string]string{}
	for name, tbl := range doc.Packages {
		pkgExtras := map[string]string{}
		for k, v := range tbl {
			if reservedKeys[k] {
				continue
			}
			rendered, err := renderTomlValue(v)
			if err != nil {
				return nil, fmt.Errorf("package %q, extra key %q: %w", name, k, err)
			}
			pkgExtras[k] = rendered
		}
		if len(pkgExtras) > 0 {
			extras[name] = pkgExtras
		}
	}
	return extras, nil
}

// renderTomlValue turns a decoded interface{} back into TOML source
// text. Handles the scalar and array types TOML/BurntSushi produce;
// nested inline tables are rejected since the standard doesn't need
// them and re-serializing them safely takes more machinery than it's
// worth here.
func renderTomlValue(v interface{}) (string, error) {
	switch val := v.(type) {
	case string:
		return strconv.Quote(val), nil
	case bool:
		return strconv.FormatBool(val), nil
	case int64:
		return strconv.FormatInt(val, 10), nil
	case float64:
		return strconv.FormatFloat(val, 'g', -1, 64), nil
	case []interface{}:
		parts := make([]string, len(val))
		for i, elem := range val {
			rendered, err := renderTomlValue(elem)
			if err != nil {
				return "", err
			}
			parts[i] = rendered
		}
		return "[" + strings.Join(parts, ", ") + "]", nil
	default:
		return "", fmt.Errorf("unsupported extra-key value type %T (only strings, bools, numbers, and arrays of those are preserved)", v)
	}
}

// BuildBumpHooks returns the per-package bump hook commands. These are
// intentionally package-scoped rather than a global cog.toml hook,
// since this monorepo has non-container package types that don't
// share this bump behavior.
func BuildBumpHooks(pkg discover.Package) []string {
	return []string{
		fmt.Sprintf(`sed -i 's/tag = ".*";/tag = "{{version}}";/' %s`, pkg.ValuesNixPath),
	}
}

// Build turns discovered packages + preserved extras into the final
// generated package set.
func Build(pkgs []discover.Package, extras map[string]map[string]string) []GeneratedPackage {
	out := make([]GeneratedPackage, 0, len(pkgs))
	for _, p := range pkgs {
		out = append(out, GeneratedPackage{
			Name:          p.Name,
			Path:          p.Dir,
			ChangelogPath: p.ValuesNixPath[:len(p.ValuesNixPath)-len("values.nix")] + "CHANGELOG.md",
			TagPrefix:     p.Name + "-",
			BumpHooks:     BuildBumpHooks(p),
			Extra:         extras[p.Name],
		})
	}
	return out
}

// Render produces the generated-section TOML text for the given
// packages, in stable sorted order.
func Render(pkgs []GeneratedPackage) string {
	sorted := make([]GeneratedPackage, len(pkgs))
	copy(sorted, pkgs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b bytes.Buffer
	for i, p := range sorted {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "[packages.%s]\n", tomlKey(p.Name))
		fmt.Fprintf(&b, "path = %s\n", strconv.Quote(p.Path))
		fmt.Fprintf(&b, "changelog_path = %s\n", strconv.Quote(p.ChangelogPath))
		fmt.Fprintf(&b, "tag_prefix = %s\n", strconv.Quote(p.TagPrefix))

		hooks := make([]string, len(p.BumpHooks))
		for i, h := range p.BumpHooks {
			hooks[i] = strconv.Quote(h)
		}
		fmt.Fprintf(&b, "bump_hooks = [%s]\n", strings.Join(hooks, ", "))

		if len(p.Extra) > 0 {
			extraKeys := make([]string, 0, len(p.Extra))
			for k := range p.Extra {
				extraKeys = append(extraKeys, k)
			}
			sort.Strings(extraKeys)
			for _, k := range extraKeys {
				fmt.Fprintf(&b, "%s = %s\n", tomlKey(k), p.Extra[k])
			}
		}
	}
	if len(sorted) > 0 {
		b.WriteString("\n")
	}
	return b.String()
}

// ComputeDiff compares old vs new package sets for --check reporting.
func ComputeDiff(oldPkgs, newPkgs []GeneratedPackage) Diff {
	oldByName := map[string]GeneratedPackage{}
	for _, p := range oldPkgs {
		oldByName[p.Name] = p
	}
	newByName := map[string]GeneratedPackage{}
	for _, p := range newPkgs {
		newByName[p.Name] = p
	}

	var d Diff
	for name := range newByName {
		if _, ok := oldByName[name]; !ok {
			d.Added = append(d.Added, name)
		}
	}
	for name := range oldByName {
		if _, ok := newByName[name]; !ok {
			d.Removed = append(d.Removed, name)
		}
	}
	for name, np := range newByName {
		if op, ok := oldByName[name]; ok && Render([]GeneratedPackage{op}) != Render([]GeneratedPackage{np}) {
			d.Changed = append(d.Changed, name)
		}
	}
	sort.Strings(d.Added)
	sort.Strings(d.Removed)
	sort.Strings(d.Changed)
	return d
}

// ParseExistingPackagesForDiff decodes the existing generated section
// into GeneratedPackage values purely for diffing against the newly
// computed set (used by --check).
func ParseExistingPackagesForDiff(generatedSuffix string) ([]GeneratedPackage, error) {
	var doc struct {
		Packages map[string]struct {
			Path          string   `toml:"path"`
			ChangelogPath string   `toml:"changelog_path"`
			TagPrefix     string   `toml:"tag_prefix"`
			BumpHooks     []string `toml:"bump_hooks"`
		} `toml:"packages"`
	}
	if strings.TrimSpace(generatedSuffix) == "" {
		return nil, nil
	}
	if _, err := toml.Decode(generatedSuffix, &doc); err != nil {
		return nil, fmt.Errorf("parsing existing generated section: %w", err)
	}
	extras, err := ParseExistingExtras(generatedSuffix)
	if err != nil {
		return nil, err
	}
	var out []GeneratedPackage
	for name, p := range doc.Packages {
		out = append(out, GeneratedPackage{
			Name:          name,
			Path:          p.Path,
			ChangelogPath: p.ChangelogPath,
			TagPrefix:     p.TagPrefix,
			BumpHooks:     p.BumpHooks,
			Extra:         extras[name],
		})
	}
	return out, nil
}

// WriteFile writes the fixed prefix + newly rendered generated suffix
// back to path.
func WriteFile(path, fixedPrefix, generatedSuffix string) error {
	final := fixedPrefix + generatedSuffix
	return os.WriteFile(path, []byte(final), 0o644)
}
