#================================================================================================================================================
# You should be able to use any of the values you can find here: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#================================================================================================================================================
image:
  repository: ghcr.io/amruthpillai/reactive-resume
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 80
        targetPort: 3000

#=============================
# RxResu specific config
#=============================
rxresu:
  apiKey: ""
  appUrl: "http://localhost:3000"
  timezone: "Etc/UTC"

  # Note: If this is set, the field apiKey won't have any effect
  configSecret:
    existingSecret: ""

  postgres:
    enabled: false

    username: rxresu
    password: ""

    port: 5432
    host: postgres-cluster-rw.postgres.svc.cluster.local

    dbName: rxresu

#=============
# Subchart(s)
#=============
