env: qa-cluster

hostnames:
  - qa-cluster-lb.lan
  - "172.18.255.200"

gitRevision: project-rockhard/backup

tekton-pipelines:
  enabled: true

authentik:
  enabled: true
  configuration:
    enabled: true

bentopdf:
  enabled: true

prowlarr:
  enabled: true
  configuration:
    enabled: true

cert-manager:
  enabled: true

seaweedfs:
  enabled: false
  configuration:
    enabled: true

homepage:
  enabled: false

vault:
  enabled: true

hashi-vault:
  configuration:
    enabled: true

vault-secrets-operator:
  configuration:
    enabled: true

metallb:
  enabled: true

metallb-config:
  configuration:
    enabled: true

istio:
  enabled: true
  configuration:
    enabled: true

ingress:
  enabled: true

kiali:
  enabled: false

kyverno:
  enabled: true
  configuration:
    enabled: true

postgres:
  enabled: true
