nextcloud:
  host: nextcloud.qa-cluster-lb.lan
  trustedDomains:
    - nextcloud.qa-cluster-lb.lan
  existingSecret:
    enabled: true
    secretName: nextcloud-config-secret
    usernameKey: username
    passwordKey: password

rbac:
  enabled: true
  serviceaccount:
    name: nextcloud
