nextcloud:
  configs:
    logging.config.php: |-
      <?php
      $CONFIG = array (
        'log_type' => 'file',
        'logfile' => 'nextcloud.log',
        'loglevel' => 0,
        'logdateformat' => 'F d, Y H:i:s'
        );
  host: nextcloud.qa-cluster-lb.lan
  trustedDomains:
    - nextcloud.qa-cluster-lb.lan
  existingSecret:
    enabled: true
    secretName: nextcloud-config-secret
    usernameKey: username
    passwordKey: password
  objectStore:
    s3:
      enabled: true
      usePathStyle: true
      host: seaweedfs-s3.seaweedfs.svc.cluster.local
      port: 8333
      bucket: nextcloud
      existingSecret: nextcloud-seaweedfs-creds
      autoCreate: false
      region: us-east-1
      ssl: false
      secretKeys:
        accessKey: accessKey
        secretKey: secretKey

persistence:
  enabled: true
  size: 1Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: postgres-cluster-rw.postgres.svc.cluster.local
  existingSecret:
    enabled: true
    secretName: nextcloud-config-secret
    usernameKey: postgresUsername
    passwordKey: postgresPassword

rbac:
  enabled: true
  serviceaccount:
    name: nextcloud
