serviceAccount:
  create: true
  name: tandoor

tandoor:
  allowedHosts: tandoor.qa-cluster-lb.lan

  configSecret:
    existingSecret: tandoor-config-secret

  postgres:
    enabled: true

  s3:
    enabled: true

    endpoint: http://seaweedfs-s3.seaweedfs.cluster.svc.local:8333
    bucket: tandoor

    configSecret:
      existingSecret: tandoor-seaweedfs-creds
