authentik:
  enabled: false
  secretDestinationNamespace: authentik
  postgresSecret: true
  destination:
    transformation:
      templates:
        AUTHENTIK_SECRET_KEY:
          text: "{{ .Secrets.secretKey }}"
        AUTHENTIK_POSTGRESQL__PASSWORD:
          text: "{{ .Secrets.postgresPassword }}"
        AUTHENTIK_POSTGRESQL__USER:
          text: "{{ .Secrets.postgresUsername }}"
  data:
    postgresUsername: authentik
    postgresPassword:
      postgresPassword: true
    secretKey: {}
    AUTHENTIK_POSTGRESQL__HOST: postgres-cluster-rw.postgres.svc.cluster.local
    AUTHENTIK_POSTGRESQL__NAME: authentik
    AUTHENTIK_BOOTSTRAP_PASSWORD: ""
    AUTHENTIK_BOOTSTRAP_TOKEN: ""
    AUTHENTIK_BOOTSTRAP_EMAIL:
      tfVar:
        name: email
        type: string
  namespace: authentik
  mount: authentik
bar-assistant:
  enabled: false
  secretDestinationNamespace: inventory-mgmt
  destination:
    transformation:
      templates:
        MEILI_MASTER_KEY:
          text: "{{ .Secrets.meilisearchApiKey }}"
  data:
    meilisearchApiKey:
      postgresPassword: false
  namespace: inventory-mgmt
  mount: inventory-mgmt
bazarr:
  enabled: false
  secretDestinationNamespace: videos
  data:
    postgresUser: bazarr
    postgresPassword:
      postgresPassword: true
    openSubtitlesUsername:
      tfVar:
        name: open_subtitles_username
        type: string
        default: user
    openSubtitlesPassword:
      tfVar:
        name: open_subtitles_password
        type: string
        default: password
  namespace: videos
  mount: videos
firefly-iii:
  enabled: false
  secretDestinationNamespace: finance
  postgresSecret: true
  serviceAccount:
    name: default
  namespace: finance
  mount: finance
  service_account: default
  data:
    postgresPassword:
      postgresPassword: true
    postgresUsername: firefly-iii
immich:
  enabled: false
  secretDestinationNamespace: immich
  postgresSecret: true
  serviceAccount:
    name: immich-server
  service_account: immich-server
  namespace: immich
  mount: immich
  data:
    postgresPassword:
      postgresPassword: true
    postgresUsername: immich
    valkeyPassword:
      postgresPassword: false
jellyfin:
  enabled: false
  secretDestinationNamespace: videos
  data:
    apiKey: {}
    password:
      postgresPassword: true
    username:
      tfVar:
        name: jellyfin_username
        type: string
        default: admin
  mount: videos
  namespace: videos
jellyseerr:
  enabled: false
  secretDestinationNamespace: videos
  data:
    apiKey: {}
  mount: videos
  namespace: videos
lidarr:
  enabled: false
  secretDestinationNamespace: music
  postgresSecret: true
  data:
    apiKey:
      postgresPassword: false
    postgresPassword:
      postgresPassword: true
    postgresUsername: lidarr
  namespace: music
  mount: music
n8n-config:
  enabled: false
  secretDestinationNamespace: n8n
  postgresSecret: true
nextcloud:
  enabled: false
  secretDestinationNamespace: nextcloud
  postgresSecret: true
  data:
    postgresUsername: nextcloud
    postgresPassword:
      postgresPassword: true
    username: admin
    password:
      postgresPassword: false
    collaboraUsername: admin
    collaboraPassword:
      postgresPassword: false
  namespace: nextcloud
  mount: nextcloud
paperless:
  enabled: false
  secretDestinationNamespace: paperless
  serviceAccount:
    name: paperless-ngx
  postgresSecret: true
  namespace: paperless
  mount: paperless
  service_account: paperless-ngx
  data:
    postgresUsername: paperless
    postgresPassword:
      postgresPassword: true
    redis-password: {}
postgres:
  enabled: false
  secretDestinationNamespace: postgres
  destination:
    type: kubernetes.io/basic-auth
    labels:
      cnpg.io/reload: ""
  serviceAccount:
    name: postgres-cluster
  data:
    password:
      postgresPassword: true
    username: postgres
  mount: postgres
  namespace: postgres
  service_account: postgres-cluster
prowlarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret: true
  data:
    apiKey:
      postgresPassword: true
    postgresPassword:
      postgresPassword: true
    postgresUsername: prowlarr
  mount: videos
  namespace: videos
radarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret: true
  data:
    apiKey:
      postgresPassword: true
    postgresPassword:
      postgresPassword: true
    postgresUsername: radarr
  mount: videos
  namespace: videos
rmfakecloud:
  enabled: false
  secretDestinationNamespace: remarkable
  namespace: remarkable
  mount: remarkable
  data:
    JWT_SECRET_KEY:
      postgresPassword: true
    RMAPI_HWR_APPLICATIONKEY:
      tfVar:
        name: hwr_applicationkey
        type: string
        default: XXXXXXX
    RMAPI_HWR_HMAC:
      tfVar:
        name: hwr_hmac
        type: string
        default: XXXXXXX
romm:
  enabled: false
  secretDestinationNamespace: romm
  postgresSecret: true
  data:
    postgresUsername: romm
    postgresPassword:
      postgresPassword: true
    rommAuthKey:
      postgresPassword: false
    redisPassword:
      postgresPassword: false
    steamGridDBApiKey:
      tfVar:
        name: steamgridDB_api_key
        type: string
        default: XXXXXXXX
    retroAchievementsApiKey:
      tfVar:
        name: retroAchievements_api_key
        type: string
        default: XXXXXXXX
  namespace: romm
  mount: romm
rxresu:
  enabled: false
  secretDestinationNamespace: misc
  postgresSecret: true
  seaweedfsSecret:
    enabled: true
  data:
    postgresUsername: rxresu
    postgresPassword:
      postgresPassword: true
    authSecret: {}
  namespace: misc
  mount: misc
seaweedfs:
  enabled: false
  secretDestinationNamespace: seaweedfs
sonarr:
  enabled: false
  secretDestinationNamespace: videos
  postgresSecret: true
  data:
    apiKey:
      postgresPassword: true
    postgresPassword:
      postgresPassword: true
    postgresUsername: sonarr
  mount: videos
  namespace: videos
tandoor:
  enabled: false
  secretDestinationNamespace: inventory-mgmt
  postgresSecret: true
  seaweedfsSecret:
    enabled: true
  data:
    postgresUsername: tandoor
    postgresPassword:
      postgresPassword: true
    secretKey: ""
  namespace: inventory-mgmt
  mount: inventory-mgmt
transmission:
  enabled: false
  secretDestinationNamespace: videos
  resourceName: vpn
  serviceAccount:
    name: transmission
  destination:
    transformation:
      templates:
        vpnConfig:
          text: |
            {{ .Secrets.vpnConfig | replace "\\n" "\n" }}
video-stack-configuration:
  enabled: false
  secretDestinationNamespace: videos
  resourceName: setup-job
  serviceAccount:
    create: true
your-spotify:
  enabled: false
  secretDestinationNamespace: your-spotify
  mount: misc
  serviceAccount:
    name: default
  namespace: your-spotify
  service_account: default
  data:
    spotifyPublic:
      tfVar:
        name: spotify_public
        type: string
        default: XXXX
    spotifyPrivate:
      tfVar:
        name: spotify_private
        type: string
        default: XXXXXXXX
    mongodbPassword: {}
video_stack_configuration:
  serviceAccounts:
    - argocd-repo-server
  auth:
    path: ""
    role_name: argocd
  data:
    jellyfinEmail:
      tfVar:
        name: email
        type: string
    jellyfinPassword:
      key_name: jellyfin-password
    jellyfinUsername:
      tfVar:
        name: jellyfin_username
        type: string
        default: admin
    jellyseerrApiKey:
      key_name: jellyseerr-apiKey
    prowlarrApiKey:
      key_name: prowlarr-apiKey
    radarrApiKey:
      key_name: radarr-apiKey
    sonarrApiKey:
      key_name: sonarr-apiKey
    lidarrApiKey:
      key_name: lidarr-apiKey
    openSubtitlesUsername:
      tfVar:
        name: open_subtitles_username
        type: string
        default: user
    openSubtitlesPassword:
      tfVar:
        name: open_subtitles_password
        type: string
        default: password
  mount: argocd
  namespace: argocd
  path: video_stack_configuration
vpn:
  data:
    VPN_AUTH:
      tfVar:
        name: vpn_auth
        type: string
    vpnConfig:
      tfVar:
        name: vpn_config
        type: string
  mount: videos
  namespace: videos
  serviceAccounts:
    - transmission
